site_name: Venture Bros Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Venture Bros Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md  
